---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shared-mongodb
  namespace: shared-services
  labels:
    app.kubernetes.io/name: shared-mongodb
    app.kubernetes.io/instance: shared-mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: ansible
    cristex.io/bootstrap-writer: ansible
    cristex.io/desired-owner: argocd
    app.kubernetes.io/part-of: shared-databases
    cristex.io/component: mongodb
automountServiceAccountToken: false
