---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infisical-keycloak-secret-writer
  namespace: shared-services
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-keycloak-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infisical-keycloak-secret-writer
subjects:
  - kind: ServiceAccount
    name: infisical-operator-controller
    namespace: shared-services
