apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-application-controller-cristexhub-prod
  namespace: cristexhub-prod
  labels:
    app.kubernetes.io/part-of: cristexhub
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: cristexhub-prod-registration
rules:
  - apiGroups: [""]
    resources: [configmaps, services]
    verbs: [get, list, watch, create, patch]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, watch, create, patch]
  - apiGroups: ['']
    resources: [serviceaccounts]
    verbs: [get, list, watch]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies, ingresses]
    verbs: [get, list, watch, create, patch]
