apiVersion: v1
kind: Service
metadata:
  name: oidc-connect-proxy
  namespace: shared-services
  labels:
    app.kubernetes.io/name: oidc-connect-proxy
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/bootstrap-writer: ansible
    cristex.io/component: oidc-connect-proxy
    cristex.io/desired-owner: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oidc-connect-proxy
  ports:
    - name: http-proxy
      port: 3128
      targetPort: http-proxy
      protocol: TCP
