apiVersion: v1
kind: ServiceAccount
metadata:
  name: shared-rabbitmq
  namespace: shared-services
  labels:
    app.kubernetes.io/name: shared-rabbitmq
    app.kubernetes.io/part-of: shared-rabbitmq
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: rabbitmq
automountServiceAccountToken: false
