---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shared-postgresql
  namespace: shared-services
  labels:
    app.kubernetes.io/name: shared-postgresql
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/bootstrap-writer: ansible
    cristex.io/component: postgresql
    cristex.io/desired-owner: argocd
automountServiceAccountToken: false
