apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalConnection
metadata:
  name: infisical-cloud
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-cristexhub-prod-runtime
  namespace: cristexhub-prod
spec:
  address: https://app.infisical.com
