---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: infisical-operator-allow-api
  namespace: shared-services
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-operator
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: infisical-operator-controller
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.43.0.1/32
      ports:
        - protocol: TCP
          port: 443
