---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: infisical-operator-allow-proxy
  namespace: shared-services
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-operator
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: infisical-operator-controller
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: infisical-egress-proxy
      ports:
        - protocol: TCP
          port: 3129
