---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: infisical-proxy-allow-dns
  namespace: shared-services
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-operator
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: infisical-egress-proxy
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
