apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reactive-resume-dev-ca-secret-writer
  namespace: cristexhub-dev
  labels:
    app.kubernetes.io/managed-by: ansible
    app.kubernetes.io/part-of: reactive-resume
    cristex.io/component: infisical-reactive-resume-dev-ca
rules:
  - apiGroups: ['']
    resources: [secrets, configmaps]
    verbs: [get, list, watch]
  - apiGroups: ['']
    resources: [secrets]
    resourceNames: [reactive-resume-dev-object-storage-ca]
    verbs: [update]
  - apiGroups: ['']
    resources: [configmaps]
    resourceNames: [reactive-resume-dev-postgresql-ca]
    verbs: [update]
  - apiGroups: ['']
    resources: [secrets, configmaps]
    verbs: [create]
