apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reactive-resume-dev-ca-secret-writer
  namespace: cristexhub-dev
  labels:
    app.kubernetes.io/managed-by: ansible
    app.kubernetes.io/part-of: reactive-resume
    cristex.io/component: infisical-reactive-resume-dev-ca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reactive-resume-dev-ca-secret-writer
subjects:
  - kind: ServiceAccount
    name: infisical-operator-controller
    namespace: shared-services
