apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: infisical-push-secret-boundary
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-operator
spec:
  policyName: infisical-push-secret-boundary
  validationActions:
  - Deny
