apiVersion: v1
kind: ServiceAccount
metadata:
  name: reactive-resume-object-storage
  namespace: shared-services
  labels:
    app.kubernetes.io/name: reactive-resume-object-storage
    app.kubernetes.io/part-of: reactive-resume
    app.kubernetes.io/managed-by: ansible
    cristex.io/bootstrap-writer: ansible
    cristex.io/desired-owner: argocd
    cristex.io/component: object-storage
automountServiceAccountToken: false
