---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-identity
  labels:
    app.kubernetes.io/part-of: cristex-platform
    cristex.io/bootstrap-writer: ansible
    cristex.io/desired-owner: argocd
