apiVersion: v1
kind: Secret
metadata:
  name: argocd-cluster-cristexhub-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cristexhub
    app.kubernetes.io/managed-by: ansible
    argocd.argoproj.io/secret-type: cluster
    cristex.io/component: cristexhub-prod-registration
type: Opaque
stringData:
  name: cristexhub-prod-local
  server: https://kubernetes.default.svc
  namespaces: cristexhub-prod
  clusterResources: "false"
  config: "{}"
