apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: cristexhub-dev-runtime
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-cristexhub-dev-runtime
  namespace: cristexhub-dev
spec:
  infisicalAuthRef:
    name: cristexhub-dev-infisical-auth
    namespace: cristexhub-dev
  syncOptions:
    refreshInterval: 1h
    instantUpdates: false
  sources:
  - projectId: 619656da-14f3-4872-857b-be103cdc5326
    environmentSlug: prod
    secretPath: /cristexhub/dev/runtime
    recursive: false
    tagSlugs: []
  targets:
  - name: cristexhub-dev-runtime
    namespace: cristexhub-dev
    kind: Secret
    secretType: Opaque
    creationPolicy: Orphan
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/managed-by: infisical
        app.kubernetes.io/part-of: cristexhub
        cristex.io/value-owner: infisical-cloud
    template:
      engineVersion: v1
      data:
        MONGODB_URL: '{{ .MONGODB_URL.Value }}'
        RABBITMQ_URL: '{{ .RABBITMQ_URL.Value }}'
        REDIS_URL: '{{ .REDIS_URL.Value }}'
        REDIS_PASSWORD: '{{ .REDIS_PASSWORD.Value }}'
        FERNET_KEY: '{{ .FERNET_KEY.Value }}'
        OIDC_CLIENT_SECRET: '{{ .OIDC_CLIENT_SECRET.Value }}'
        OAUTH2_PROXY_COOKIE_SECRET: '{{ .OAUTH2_PROXY_COOKIE_SECRET.Value }}'
