---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shared-postgresql-default-deny
  namespace: shared-services
  labels:
    app.kubernetes.io/name: shared-postgresql
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/bootstrap-writer: ansible
    cristex.io/component: postgresql
    cristex.io/desired-owner: argocd
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: shared-postgresql
      app.kubernetes.io/part-of: cristex-platform
  policyTypes:
    - Ingress
    - Egress
