---
apiVersion: v1
kind: Service
metadata:
  name: shared-rabbitmq-management
  namespace: shared-services
  labels:
    app.kubernetes.io/name: shared-rabbitmq
    app.kubernetes.io/part-of: shared-rabbitmq
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: rabbitmq
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: shared-rabbitmq
    app.kubernetes.io/part-of: shared-rabbitmq
  ports:
  - name: mgmt-https
    port: 15671
    targetPort: mgmt-https
    protocol: TCP
