apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: shared-services
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/bootstrap-writer: ansible
    cristex.io/component: keycloak
    cristex.io/desired-owner: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: cristex-platform
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
