apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reactive-resume-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: reactive-resume-dev
    app.kubernetes.io/part-of: cristexhub
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: reactive-resume-dev-argocd-registration
spec:
  project: reactive-resume-dev
  source:
    repoURL: ssh://git@ssh.github.com:443/devraider/cristexweb.git
    targetRevision: 7d1c33c5abfbfe86d942bc3d887a95b5cdc2760c
    path: ansible/files/components/reactive-resume-dev-argocd
  destination:
    name: reactive-resume-dev-local
    server: ''
    namespace: cristexhub-dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - Prune=false
      - ServerSideApply=false
      - Replace=false
      - FailOnSharedResource=true
