apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reactive-resume-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: reactive-resume-dev
    app.kubernetes.io/part-of: cristexhub
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: reactive-resume-dev-argocd-registration
spec:
  project: reactive-resume-dev
  source:
    repoURL: ssh://git@ssh.github.com:443/devraider/cristexweb.git
    targetRevision: dd7d4cedd902e68266d9713d1dbb8e90f0b529b1
    path: ansible/files/components/reactive-resume-dev-argocd
  destination:
    name: ''
    server: https://kubernetes.default.svc
    namespace: cristexhub-dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - Prune=false
      - ServerSideApply=false
      - Replace=false
      - FailOnSharedResource=true
