apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cristexhub-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: cristexhub-dev
    app.kubernetes.io/part-of: cristexhub
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: cristexhub-dev-sync-transition
spec:
  project: cristexhub-dev
  source:
    repoURL: ssh://git@ssh.github.com:443/devraider/cristexhub.git
    targetRevision: a186195afa2af76cf38f53903b92724a74d4ef13
    path: infra/kubernetes/cristexhub-dev
  destination:
    name: cristexhub-dev-local
    server: ''
    namespace: cristexhub-dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - Prune=false
      - ServerSideApply=false
      - Replace=false
      - FailOnSharedResource=true
