---
apiVersion: v1
kind: Namespace
metadata:
  name: cristexhub-dev
  labels:
    app.kubernetes.io/part-of: cristexhub
    cristex.io/environment: dev
    cristex.io/bootstrap-writer: ansible
    cristex.io/desired-owner: argocd
