---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-postgresql-pg-hba
  namespace: shared-services
  labels:
    app.kubernetes.io/name: shared-postgresql
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/bootstrap-writer: ansible
    cristex.io/component: postgresql
    cristex.io/desired-owner: argocd
data:
  pg_hba.conf: |
    local all all scram-sha-256
    hostssl all all 127.0.0.1/32 scram-sha-256
    hostssl all all ::1/128 scram-sha-256
    hostssl all all 10.42.0.0/16 scram-sha-256
    hostnossl all all 0.0.0.0/0 reject
    hostnossl all all ::/0 reject
    host all all 0.0.0.0/0 reject
    host all all ::/0 reject
