apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: infisical-cristexhub-dev-runtime-alternate-target-boundary
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-cristexhub-dev-runtime
spec:
  policyName: infisical-cristexhub-dev-runtime-alternate-target-boundary
  validationActions:
  - Deny
