---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: reactive-resume-dev-migration
  namespace: cristexhub-dev
  labels:
    app.kubernetes.io/managed-by: ansible
    app.kubernetes.io/part-of: reactive-resume
    cristex.io/component: reactive-resume-dev-successor
    cristex.io/environment: dev
spec:
  infisicalAuthRef:
    name: cristexhub-dev-infisical-auth
    namespace: cristexhub-dev
  syncOptions:
    refreshInterval: 1h
    instantUpdates: false
  sources:
    - projectId: 619656da-14f3-4872-857b-be103cdc5326
      environmentSlug: prod
      secretPath: /reactive-resume/dev/migration
      recursive: false
      tagSlugs: []
  targets:
    - name: reactive-resume-dev-migration
      namespace: cristexhub-dev
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: reactive-resume
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          DATABASE_URL: '{{ .DATABASE_URL.Value }}'
          MIGRATION_DATABASE_URL: '{{ .MIGRATION_DATABASE_URL.Value }}'
