---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infisical-operator-leader-election
  namespace: shared-services
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-operator
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
