---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-egress-proxy
  namespace: shared-services
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-operator
automountServiceAccountToken: false
