apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-application-controller-cristexhub-dev
  namespace: cristexhub-dev
  labels:
    app.kubernetes.io/part-of: cristexhub
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: cristexhub-dev-registration
rules:
  - apiGroups: [""]
    resources: [configmaps, services]
    verbs: [get, list, watch, create, patch]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, watch, create, patch]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies]
    verbs: [get, list, watch, create, patch]
