---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: ansible
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.5.0-sha256-521d6b62ecd0434c9cc6e9242a74f0e1137bb8fc0026b2c48
    cristex.io/component: argocd
data:
  server.insecure: 'true'
  server.disable.auth: 'false'
  server.enable.proxy.extension: 'false'
  reposerver.enable.git.submodule: 'false'
  reposerver.allow.oob.symlinks: 'false'
  redis.server: argocd-redis:6379
  repo.server: argocd-repo-server:8081
