apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infisical-cristexhub-dev-runtime-secret-writer
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-cristexhub-dev-runtime
  namespace: cristexhub-dev
rules:
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ''
    resources:
    - secrets
    resourceNames:
    - cristexhub-dev-runtime
    verbs:
    - update
  - apiGroups:
    - ''
    resources:
    - secrets
    verbs:
    - create
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - statefulsets
    verbs:
    - list
    - watch
