---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: shared-postgresql-infisical-secrets
  namespace: shared-services
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-database-secrets
spec:
  infisicalAuthRef:
    name: shared-postgresql-infisical-auth
    namespace: shared-services
  syncOptions:
    refreshInterval: 1h
    instantUpdates: false
  sources:
    - projectSlug: cristexweb-infrastructure
      environmentSlug: bootstrap
      secretPath: /shared-services/postgresql
      recursive: false
      tagSlugs: []
  targets:
    - name: shared-postgresql-admin
      namespace: shared-services
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: shared-databases
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          username: '{{ .POSTGRESQL_ADMIN_USERNAME.Value }}'
          password: '{{ .POSTGRESQL_ADMIN_PASSWORD.Value }}'
    - name: shared-postgresql-tls
      namespace: shared-services
      kind: Secret
      secretType: kubernetes.io/tls
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: shared-databases
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          ca.crt: '{{ .POSTGRESQL_TLS_CA_CRT.Value }}'
          tls.crt: '{{ .POSTGRESQL_TLS_CRT.Value }}'
          tls.key: '{{ .POSTGRESQL_TLS_KEY.Value }}'
    - name: shared-postgresql-cristexhub-dev
      namespace: shared-services
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: shared-databases
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          username: '{{ .POSTGRESQL_CRISTEXHUB_DEV_USERNAME.Value }}'
          password: '{{ .POSTGRESQL_CRISTEXHUB_DEV_PASSWORD.Value }}'
    - name: shared-postgresql-cristexhub-prod
      namespace: shared-services
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: shared-databases
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          username: '{{ .POSTGRESQL_CRISTEXHUB_PROD_USERNAME.Value }}'
          password: '{{ .POSTGRESQL_CRISTEXHUB_PROD_PASSWORD.Value }}'
    - name: shared-postgresql-reactive-resume-dev
      namespace: shared-services
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: shared-databases
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          username: '{{ .POSTGRESQL_REACTIVE_RESUME_DEV_USERNAME.Value }}'
          password: '{{ .POSTGRESQL_REACTIVE_RESUME_DEV_PASSWORD.Value }}'
    - name: shared-postgresql-reactive-resume-prod
      namespace: shared-services
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: shared-databases
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          username: '{{ .POSTGRESQL_REACTIVE_RESUME_PROD_USERNAME.Value }}'
          password: '{{ .POSTGRESQL_REACTIVE_RESUME_PROD_PASSWORD.Value }}'
    - name: shared-postgresql-keycloak
      namespace: shared-services
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: shared-databases
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          username: '{{ .POSTGRESQL_KEYCLOAK_USERNAME.Value }}'
          password: '{{ .POSTGRESQL_KEYCLOAK_PASSWORD.Value }}'
