---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalConnection
metadata:
  name: infisical-cloud
  namespace: shared-services
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-keycloak-secrets
spec:
  address: https://app.infisical.com/api
