---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: argocd-infisical-auth
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-argocd-secrets
spec:
  infisicalConnectionRef:
    name: infisical-cloud
    namespace: argocd
  method: universal
  universal:
    clientIdRef:
      name: argocd-infisical-universal-auth
      namespace: argocd
      key: clientId
    clientSecretRef:
      name: argocd-infisical-universal-auth
      namespace: argocd
      key: clientSecret
