---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: argocd-infisical-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-argocd-secrets
spec:
  infisicalAuthRef:
    name: argocd-infisical-auth
    namespace: argocd
  syncOptions:
    refreshInterval: 5m
    instantUpdates: false
  sources:
    - projectId: 619656da-14f3-4872-857b-be103cdc5326
      environmentSlug: prod
      secretPath: /argocd
      recursive: false
      tagSlugs: []
  targets:
    - name: argocd-secret
      namespace: argocd
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: argocd
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          admin.password: '{{ .ARGOCD_ADMIN_PASSWORD_BCRYPT.Value }}'
          admin.passwordMtime: '{{ .ARGOCD_ADMIN_PASSWORD_MTIME.Value }}'
          server.secretkey: '{{ .ARGOCD_SERVER_SECRETKEY.Value }}'
    - name: argocd-redis
      namespace: argocd
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: argocd
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          auth: '{{ .ARGOCD_REDIS_AUTH.Value }}'
    - name: argocd-server-tls
      namespace: argocd
      kind: Secret
      secretType: kubernetes.io/tls
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: argocd
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          ca.crt: '{{ .ARGOCD_TLS_CA_CRT.Value }}'
          tls.crt: '{{ .ARGOCD_TLS_CRT.Value }}'
          tls.key: '{{ .ARGOCD_TLS_KEY.Value }}'
    - name: argocd-repository-cristexhub
      namespace: argocd
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: argocd
          argocd.argoproj.io/secret-type: repository
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          type: git
          url: ssh://git@ssh.github.com:443/devraider/cristexhub.git
          sshPrivateKey: '{{ .ARGOCD_CRISTEXHUB_REPOSITORY_SSH_PRIVATE_KEY.Value }}'
    - name: argocd-repository-cristexweb
      namespace: argocd
      kind: Secret
      secretType: Opaque
      creationPolicy: Orphan
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/managed-by: infisical
          app.kubernetes.io/part-of: argocd
          argocd.argoproj.io/secret-type: repository
          cristex.io/value-owner: infisical-cloud
      template:
        engineVersion: v1
        data:
          type: git
          url: ssh://git@ssh.github.com:443/devraider/cristexweb.git
          sshPrivateKey: '{{ .ARGOCD_CRISTEXWEB_REPOSITORY_SSH_PRIVATE_KEY.Value }}'
