---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: infisical-rabbitmq-static-secret-boundary
  labels:
    app.kubernetes.io/part-of: cristex-platform
    app.kubernetes.io/managed-by: ansible
    cristex.io/component: infisical-rabbitmq-secrets
spec:
  policyName: infisical-rabbitmq-static-secret-boundary
  validationActions: [Deny]
