apiVersion: batch/v1
kind: Job
metadata:
  name: reactive-resume-dev-migrate
  namespace: cristexhub-dev
  labels:
    app.kubernetes.io/name: reactive-resume-dev-migrate
    app.kubernetes.io/part-of: cristexhub
    app.kubernetes.io/managed-by: ansible
    cristex.io/bootstrap-writer: ansible
    cristex.io/desired-owner: argocd
