apiVersion: v1
kind: ServiceAccount
metadata:
  name: reactive-resume-dev
  namespace: cristexhub-dev
  labels:
    app.kubernetes.io/name: reactive-resume-dev
    app.kubernetes.io/part-of: cristexhub
    app.kubernetes.io/managed-by: ansible
    cristex.io/bootstrap-writer: ansible
    cristex.io/desired-owner: argocd
